
ecasa:
  security:
    secret: ZGYwMTMxYjg1ZjJkNDgwYmI4MDQzMjI4MGI3NTg4YzI5ZDgzY2FhMTZmM2JkMTNkNzYwOTIyOTNmMjk3YTM3OTI4MTdiNjdmYTYwZGI0M2Q3OTliYzBhOGVjYjI3OTA2YjIzZGNmMmU2OGNhODQ3NjNmM2M5YjY4N2FmZWIwZDg=